### ISSUE TITLE
Software Updater/Software & Updates issues

### ISSUE THREAD

**Issue by Dasein123** [wimpysworld/rolling-rhino#40]
in addition to https://github.com/wimpysworld/rolling-rhino/issues/39

there are also errors when trying to access or view software repositories settings in either app manager or from the Ubuntu Updater. From the /usr/bin/update-manager command line it says

Traceback (most recent call last):
  File "/usr/bin/software-properties-gtk", line 100, in <module>
    app = SoftwarePropertiesGtk(datadir=options.data_dir, options=options, file=file)
  File "/usr/lib/python3/dist-packages/softwareproperties/gtk/SoftwarePropertiesGtk.py", line 154, in __init__
    SoftwareProperties.__init__(self, options=options, datadir=datadir)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 111, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 605, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Ubuntu/hirsute

gks gedit /etc/lsb-release - don't know what to put in this file since I just have the names devel and hirsuite to try and fix it

the sudo apt-get update && sudo apt-get upgrade command seems to work but show the errors listed in the previously linked issue, i was able to fix some of those errors however

**Comment by Dasein123** [comment]
I've seen the sudo rm -rvf /var/lib/apt/lists/* command as a solution but unsure about trying it with this

what do you guys think?
